wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1648981157
    t:
      3:
      - 2
      - 13
      - 14
      - 16
      4: 3.9.7
      5: 0.12.11
      8:
      - 3
      - 5
created_at:
  desc: null
  value: '2022-04-03T05:53:18'
fine_tuned_model:
  desc: null
  value: babbage:ft-personal:eugenics-001-2022-04-03-09-54-56
hyperparams:
  desc: null
  value:
    batch_size: 1
    learning_rate_multiplier: 0.05
    n_epochs: 4
    prompt_loss_weight: 0.1
id:
  desc: null
  value: ft-oQ3zigVLl1UdXMYaJjyJSjVL
model:
  desc: null
  value: babbage
n_train:
  desc: null
  value: 17
object:
  desc: null
  value: fine-tune
organization_id:
  desc: null
  value: org-Q1zQjUFbaRekSJPJKRcyo2SC
result_files:
  desc: null
  value:
    bytes: 3027
    created_at: 1648979699
    filename: compiled_results.csv
    id: file-DQ0n1KonqO1BH4gd1wqi7oet
    object: file
    purpose: fine-tune-results
    status: processed
    status_details: null
status:
  desc: null
  value: succeeded
training_files:
  desc: null
  value:
    bytes: 1799
    created_at: 1648979597
    filename: data.jsonl
    id: file-HYLndFf8PI6pbLzLqnNBev6v
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
updated_at:
  desc: null
  value: 1648979702
validation_files:
  desc: null
  value: []
